### PR TITLE
Add support for latest Intel Pin (3.7)

### PR DESCRIPTION
**Pull request by RKX1209**
Ported taint analysis library libdft64 for PinCRT which is used as a C/C++ runtime framework in Intel Pin (>=3.0).
There are some changes in both components libdft64 and vuzzer64.
### libdft64
- Change build method to use default Makefile from Pin
- Port source codes for PinCRT.
### vuzzer64
- Add bb shell script (In some distributions, python's subprocess doesn't work correctly for hard coded "--" (double dash).
- Use latest pin binary (pin.sh was deprecated)

### CODE REVIEW

**Comment by tosanjay** [comment]
Hi Ren,
This is really great. Just a quick query: Have you done some testing on couple of applications? If so, can you please let us know which applications you tested with?
Again, thanks for this patch :)

**Comment by RKX1209** [comment]
Hi. Is their any progress?

**Comment by tosanjay** [comment]
Hi,I will merge it soon (as currently i am traveling). as of now, it seems promising.
 
Thanks & Regards
- Sanjay
https://sites.google.com/site/securitythoughts/ 

    On Wednesday, November 28, 2018, 2:53:30 AM GMT+5:30, Ren Kimura <notifications@github.com> wrote:  
 
 
Hi. Is their any progress?

**Comment by RKX1209** [comment]
Sorry, I forgot noted that PinCRT doesn't support some C++11 features like vector->data().
We need to use older version of EWAHBoolArray (actually I used ver 0.4.0)

**Comment by tosanjay** [comment]
Hi,
your pull request is merged. Thank you very much :)

**Comment by vanhauser-thc** [comment]
the README still says PIN 2.13 is required - is that outdated or are there othe requirements why it still must be that old version?

**Pull request merged**
